In [1]:
import torch
import torch.nn as nn
import numpy as np
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_log_error
from sklearn.metrics import root_mean_squared_error
from scipy.ndimage import shift
import math
from functools import lru_cache
from multiprocessing.pool import ThreadPool
from functools import partial

# Data preparation

In [2]:
NM_data = pd.read_csv('../data/LMKS_NM_1981-2023_hour.csv')
data = pd.read_csv('../data/omni_full_1964-2022.csv')
data

,Unnamed: 0,time1,Rot$,IMF,PLS,IMF_PTS,PLS_PTS,ABS_B,F,THETA_AV,...,F10_INDEX+48,BZ_GSE+1,BZ_GSE+2,BZ_GSE+3,BZ_GSE+4,BZ_GSE+6,BZ_GSE+8,BZ_GSE+12,BZ_GSE+24,BZ_GSE+48
0,0,1963-01-01 01:00:00,1771.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1963-01-01 02:00:00,1771.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1963-01-01 03:00:00,1771.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1963-01-01 04:00:00,1771.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1963-01-01 05:00:00,1771.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
520438,520438,2022-05-13 12:00:00,9999.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,...,135.600006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520439,520439,2022-05-13 13:00:00,9999.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,...,135.600006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520440,520440,2022-05-13 14:00:00,9999.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,...,135.600006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520441,520441,2022-05-13 15:00:00,9999.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,...,135.600006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
520442,520442,2022-05-13 16:00:00,9999.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,...,135.600006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
NM_data.index = NM_data['Unnamed: 0']
NM_data.drop("Unnamed: 0", axis=1, inplace=True)
NM_data

                       H_COR
Unnamed: 0
1981-12-01 00:00:00  87.2680
1981-12-01 01:00:00  86.9240
1981-12-01 02:00:00  86.8670
1981-12-01 03:00:00  86.4080
1981-12-01 04:00:00  86.5230
...                      ...
2023-07-10 19:00:00  92.4196
2023-07-10 20:00:00  92.4196
2023-07-10 21:00:00  92.4196
2023-07-10 22:00:00  92.4196
2023-07-10 23:00:00  92.4196

[364728 rows x 1 columns]

In [4]:
NM_data.dropna(inplace=True)
NM_data.isna().sum()

H_COR    0
dtype: int64

In [5]:
data.drop('Unnamed: 0', axis=1, inplace=True)
data.index = data['time1']
data.drop('time1', axis=1, inplace=True)
data

,Rot$,IMF,PLS,IMF_PTS,PLS_PTS,ABS_B,F,THETA_AV,PHI_AV,BX_GSE,...,F10_INDEX+48,BZ_GSE+1,BZ_GSE+2,BZ_GSE+3,BZ_GSE+4,BZ_GSE+6,BZ_GSE+8,BZ_GSE+12,BZ_GSE+24,BZ_GSE+48
time1,,,,,,,,,,,,,,,,,,,,,
1963-01-01 01:00:00,1771.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1963-01-01 02:00:00,1771.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1963-01-01 03:00:00,1771.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1963-01-01 04:00:00,1771.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1963-01-01 05:00:00,1771.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-05-13 12:00:00,9999.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,NaN,NaN,...,135.600006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-05-13 13:00:00,9999.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,NaN,NaN,...,135.600006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-05-13 14:00:00,9999.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,NaN,NaN,...,135.600006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-05-13 15:00:00,9999.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,NaN,NaN,...,135.600006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022-05-13 16:00:00,9999.0,99.0,99.0,999.0,999.0,NaN,NaN,NaN,NaN,NaN,...,135.600006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data_relevant = data[['BZ_GSE', 'V', 'N', 'DST', 'SIGMA$Bz']].loc["1995-01-01 00:00:00":]
data_relevant.isna().sum()

BZ_GSE       977
V            903
N           5586
DST            0
SIGMA$Bz     977
dtype: int64

In [7]:
data_relevant.index = pd.to_datetime(data_relevant.index)
data_relevant_interpolated = data_relevant.interpolate(method='time')
data_relevant_interpolated.isna().sum()

BZ_GSE      0
V           0
N           0
DST         0
SIGMA$Bz    0
dtype: int64

## Intersection of omni data and NM data

In [8]:
data_relevant_interpolated.index = pd.to_datetime(data_relevant_interpolated.index)
NM_data.index = pd.to_datetime(NM_data.index)

common_index = data_relevant_interpolated.index.intersection(NM_data.index)

data_relevant_interpolated_common = data_relevant_interpolated.loc[common_index]
nm_data_common = NM_data.loc[common_index]

data_relevant_interpolated_common['NM'] = nm_data_common.iloc[:, 0]
data_relevant_interpolated = data_relevant_interpolated_common

data_relevant_interpolated.isna().sum()

BZ_GSE      0
V           0
N           0
DST         0
SIGMA$Bz    0
NM          0
dtype: int64

## Data normalization

In [9]:
min_val = data_relevant_interpolated.min()
max_val = data_relevant_interpolated.max()

# Normalize between -1 and 1
data_relevant_interpolated_normalized = 2 * (data_relevant_interpolated - min_val) / (max_val - min_val) - 1
data_relevant_interpolated_normalized

,BZ_GSE,V,N,DST,SIGMA$Bz,NM
1995-01-01 00:00:00,0.131579,-0.818939,-0.763676,0.683367,-0.976134,0.412806
1995-01-01 00:00:00,0.131579,-0.818939,-0.763676,0.683367,-0.976134,0.412806
1995-01-01 01:00:00,0.149123,-0.818939,-0.727206,0.703407,-0.961814,0.405224
1995-01-01 02:00:00,0.168860,-0.808533,-0.719912,0.715431,-0.914081,0.403689
1995-01-01 03:00:00,0.184211,-0.814776,-0.762217,0.711423,-0.961814,0.399131
...,...,...,...,...,...,...
2022-05-13 12:00:00,0.184211,-0.829344,-0.905179,0.699399,-0.904535,0.714550
2022-05-13 13:00:00,0.184211,-0.829344,-0.905179,0.707415,-0.904535,0.715932
2022-05-13 14:00:00,0.184211,-0.829344,-0.905179,0.711423,-0.904535,0.717940
2022-05-13 15:00:00,0.184211,-0.829344,-0.905179,0.711423,-0.904535,0.707895
2022-05-13 16:00:00,0.184211,-0.829344,-0.905179,0.707415,-0.904535,0.701796

# Regression model

In [10]:
data_relevant_interpolated_normalized

,BZ_GSE,V,N,DST,SIGMA$Bz,NM
1995-01-01 00:00:00,0.131579,-0.818939,-0.763676,0.683367,-0.976134,0.412806
1995-01-01 00:00:00,0.131579,-0.818939,-0.763676,0.683367,-0.976134,0.412806
1995-01-01 01:00:00,0.149123,-0.818939,-0.727206,0.703407,-0.961814,0.405224
1995-01-01 02:00:00,0.168860,-0.808533,-0.719912,0.715431,-0.914081,0.403689
1995-01-01 03:00:00,0.184211,-0.814776,-0.762217,0.711423,-0.961814,0.399131
...,...,...,...,...,...,...
2022-05-13 12:00:00,0.184211,-0.829344,-0.905179,0.699399,-0.904535,0.714550
2022-05-13 13:00:00,0.184211,-0.829344,-0.905179,0.707415,-0.904535,0.715932
2022-05-13 14:00:00,0.184211,-0.829344,-0.905179,0.711423,-0.904535,0.717940
2022-05-13 15:00:00,0.184211,-0.829344,-0.905179,0.711423,-0.904535,0.707895
2022-05-13 16:00:00,0.184211,-0.829344,-0.905179,0.707415,-0.904535,0.701796

In [11]:
DST_shift = data_relevant_interpolated_normalized['DST'].shift(1)
DST_shift.fillna(value=0,inplace=True)
DST_shift

1995-01-01 00:00:00    0.000000
1995-01-01 00:00:00    0.683367
1995-01-01 01:00:00    0.683367
1995-01-01 02:00:00    0.703407
1995-01-01 03:00:00    0.715431
                         ...
2022-05-13 12:00:00    0.699399
2022-05-13 13:00:00    0.699399
2022-05-13 14:00:00    0.707415
2022-05-13 15:00:00    0.711423
2022-05-13 16:00:00    0.711423
Name: DST, Length: 239877, dtype: float64

In [12]:
N = data_relevant_interpolated_normalized['N'].to_numpy()
V = data_relevant_interpolated_normalized['V'].to_numpy()
NV = N * V
Bz= data_relevant_interpolated_normalized['BZ_GSE'].to_numpy()
sigma_bz = data_relevant_interpolated_normalized['SIGMA$Bz'].to_numpy()
nm = data_relevant_interpolated_normalized['NM'].to_numpy()
DST = data_relevant_interpolated_normalized['DST'].to_numpy()

Definicia persistancneho modela ako linearana kombinacia zvysnych parametrov modelu FFNN.
$$
DST_{t+1} = DST_t + \sum_{i = 1}^{|N|} = \omega_i(\psi_i - \psi_i^{ref})
$$
To iste v podobe matic a vektorov.
$$
\vec{y} = \vec{\beta} + \mathbf{X}\vec{\omega}
$$

In [13]:
y = DST_shift.to_numpy()
b = data_relevant_interpolated_normalized['DST'].to_numpy()
b.shape, y.shape

((239877,), (239877,))

## Vypocet matice $X$

In [14]:
X = []

In [15]:
N_mean = N.mean()
NV_mean = NV.mean()
V_mean = V.mean()
Bz_mean = Bz.mean()
sigma_bz_mean = sigma_bz.mean()
nm_mean = nm.mean()
N_mean, V_mean, Bz_mean, sigma_bz_mean, nm_mean, NV_mean

(np.float64(-0.9092295346299987),
 np.float64(-0.5875355186766423),
 np.float64(0.1771662958918724),
 np.float64(-0.9377969344570631),
 np.float64(0.4876614210538083),
 np.float64(0.5285874443950322))

In [16]:
params = [N, V, Bz, sigma_bz, nm]

In [17]:
X = np.array([
    N - N_mean, V - V_mean, Bz - Bz_mean, sigma_bz - sigma_bz_mean, nm - nm_mean, NV - NV_mean
])
X.shape, X.T.shape

((6, 239877), (239877, 6))

In [18]:
X = X.T
X.shape

(239877, 6)

## Vypocet vah
$$
\vec{\omega} = (\mathbf{X}^T\mathbf{X})^{-1}\mathbf{X}^T(\vec{y} - \vec{\beta})
$$

In [19]:
w = (np.linalg.inv(X.T @ X) @ X.T) @ (y - b)

In [20]:
w

array([ 0.06198545,  0.08515494, -0.08380987,  0.02530192,  0.00141577,
        0.09118692])

## Finalny model

In [21]:
persistance = b + np.sum(X*w, axis=1)

In [22]:
persistance

array([0.6842569 , 0.6842569 , 0.70271538, ..., 0.71191417, 0.71189995,
       0.7078833 ], shape=(239877,))

In [23]:
%matplotlib qt
plt.plot(y, label='DST_t+1')
plt.plot(persistance, label='prediction')
plt.legend()

In [24]:
mean_squared_error(y, persistance)

0.0002600635399853744

# Shapely values
Nech $\psi$ je nejaky parameter, $P$ je mnozina parametrov a $f : P \rightarrow DST_{t+1}$ je model a $x_0$ je jedna hodnota DST. Potom shapely hodnota parametru $\psi$ v bode $x_0$ je
$$
\varphi_{\psi}(x_0) = \frac{1}{|P|!} \sum_{S \subseteq P \setminus \{\psi\}} |S|!\cdot(|P| - |S| - 1)! \cdot (f(S \cup \{\psi\}) - f(S))
$$
Vypocet si bude vyzadovat postavit niekolko krokov.
- Napjprv je potrebne spravit **mnozinu podmnozin** mnoziny $P$
- Vytvorit **funkciu** ktora **vytvori model s novym poctom parametrov** na vstupe, kedze $f(S)$ bude vzdy predikcia modelu s inym poctom parametrov.
- Skombinovat

## Mnozina podmnozin $P$
Na $S \subseteq P \setminus \{\psi\}$ sa mozeme pozerat trochu inak. V podstate to hovori ze $S$ je kazda podmnozina mnoziny $P$. Preto mozeme zapisat $S$ ako $S \subseteq \mathcal{P(\mathbf{P})}$, cize $S$ je kazda mnozina potencnej mnozinu $P$.

In [25]:
from itertools import chain, combinations

def powerset(iterable):
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(len(s)+1))

In [26]:
AllParams = [N, V, Bz, sigma_bz, nm, DST]

In [27]:
def power_set_minus(P, target):
    new_P = []
    for i in P:
        if i == target: continue
        else: new_P.append(i)
    power_P = list(powerset(new_P))

    return power_P

## Dynamicky persistencny model

In [28]:
def f(P, y, b):
    '''
        P - set of parameters ([N, V, Bz,...]) (2D matrix)
        y - DST_t+1 (array)
        b - DST_t   (array)
    '''
    if not P: return np.array([])
    X = np.array([
        p - p.mean() for p in P 
    ])
    X = X.T

    w = (np.linalg.inv(X.T @ X) @ X.T) @ (y - b)

    return w

def pp(X, b, w):
    '''
        X - shape [p1 - p1_mean, p2 - p2_mean, ...]
        b - shape [DST1, DST2, DST3]
        w - weights for parameters p_1 - p_n
    '''
    X = X.T
    if len(X.shape) <= 1: return b + np.sum(X*w)
    else: return b + np.sum(X*w, axis=1)

In [29]:
f([], y, b)

array([], dtype=float64)

In [30]:
pp(
    np.array([N[10] - N.mean(), V[10] - V.mean(), Bz[10] - Bz.mean(), sigma_bz[10] - sigma_bz.mean(), nm[10] - nm.mean(), NV[10] - NV.mean()]),
    b[10],
    f([N, V, Bz, sigma_bz, nm, NV], y, b)
)

np.float64(0.6985369524786599)

## Shapely values calculation

In [82]:
@lru_cache(maxsize=None)
def shapely2(P, T, i):
    '''
    P - set of parameters
    T - target parameter, integer value from mask
    i - index of data-point in dataset
    '''

    mask = [i for i in range(len(P))]
    DST_idx = len(P)-1

    pset = power_set_minus(mask, T)

    SUM = 0
    for S in pset:        
        '''
        Creating model
        '''
        X = None
        b = None
        if DST_idx in S:
            b = P[DST_idx]
            S = S[:-1]
            X = [P[k][i] - P[k].mean() for k in S]
        else:
            b = np.zeros(len(P[DST_idx]))
            X = [P[k][i] - P[k].mean() for k in S]

        # contribution value f(S U {i}) - f(S)
        if T != DST_idx:
            # f(S)
            prediction = pp(np.array(X), b[i], f([P[k] for k in S], y, b))

            # f(S U {i}) 
            S = list(S)
            S.append(T)
            X.append(P[T][i] - P[T].mean())
            prediction_w_target = pp(np.array(X), b[i], f([P[k] for k in S], y, b))

            # f(S U {i}) - f(S)
            contrib = prediction_w_target - prediction
        
            # multiplication factor |S|! * (|P| - |S| - 1)!
            mult_factor = math.factorial(len(S)) * math.factorial((len(P) - len(S) - 1))

            SUM += mult_factor * contrib
            
        else:
            # f(S)
            prediction = pp(np.array(X), b[i], f([P[k] for k in S], y, b))

            # f(S U {i}) 
            b = P[DST_idx]
            prediction_w_target = pp(np.array(X), b[i], f([P[k] for k in S], y, b))

            # f(S U {i}) - f(S)
            contrib = prediction_w_target - prediction

            # multiplication factor |S|! * (|P| - |S| - 1)!
            mult_factor = math.factorial(len(S)) * math.factorial((len(P) - len(S) - 1))

            SUM += mult_factor * contrib

    return (SUM / math.factorial(len(P))).item()


weight_cache = {}

def cached_f(P, y, b):
    key = tuple(sorted([id(p) for p in P]))
    if key not in weight_cache:
        weight_cache[key] = f(P, y, b)
    return weight_cache[key]

def compute_contribution(means, P, T, i, S_tuple):
    DST_idx = len(P) - 1
    S = list(S_tuple)


    X = None
    b = None
    if DST_idx in S:
        b = P[DST_idx]
        S = S[:-1]
        X = [P[k][i] - means[k] for k in S]
    else:
        b = np.zeros(len(P[DST_idx]))
        X = [P[k][i] - means[k] for k in S]

    # contribution value f(S U {i}) - f(S)
    if T != DST_idx:
        # f(S)
        prediction = pp(np.array(X), b[i], f([P[k] for k in S], y, b))

        # f(S U {i}) 
        S = list(S)
        S.append(T)
        X.append(P[T][i] - means[T])
        prediction_w_target = pp(np.array(X), b[i], f([P[k] for k in S], y, b))

        # f(S U {i}) - f(S)
        contrib = prediction_w_target - prediction
    
        # multiplication factor |S|! * (|P| - |S| - 1)!
        mult_factor = math.factorial(len(S)) * math.factorial((len(P) - len(S) - 1))

        return mult_factor * contrib
        
    else:
        # f(S)
        prediction = pp(np.array(X), b[i], f([P[k] for k in S], y, b))

        # f(S U {i}) 
        b = P[DST_idx]
        prediction_w_target = pp(np.array(X), b[i], f([P[k] for k in S], y, b))

        # f(S U {i}) - f(S)
        contrib = prediction_w_target - prediction

        # multiplication factor |S|! * (|P| - |S| - 1)!
        mult_factor = math.factorial(len(S)) * math.factorial((len(P) - len(S) - 1))

        return mult_factor * contrib

def shapely_optimized(P, T, i, num_workers=None):
    """
    Optimized Shapley value calculation
    
    P - set of parameters
    T - target parameter index
    i - index of data-point in dataset
    num_workers - number of parallel workers (None for auto)
    """
    mask = list(range(len(P)))
    all_subsets = [tuple(s) for s in power_set_minus(mask, T)]
    means = {k: P[k].mean() for k in range(len(P))}
    
    worker = partial(compute_contribution, means, P, T, i)
    
    # Parallel processing
    with ThreadPool(processes=num_workers) as pool:
        results = pool.map(worker, all_subsets)
    
    total = sum(results)
    return (total / math.factorial(len(P))).item()


def shapely_gpt_optimizes(P, T, i):
    pass

In [83]:
shapely_optimized(AllParams, 0, 0, 10)

0.011146978728545169

## Calculate shapely values for all parameters

In [ ]:

%%time
Shapely_all_params_mean = []
event_start = 77200
event_end   = 77500

for p in range(len(AllParams)):
    temp = 0
    for e in range(event_start, event_end):
        temp += shapely_optimized(
            AllParams,
            p,
            e,
            20
        )
        print(p, e)
    Shapely_all_params_mean.append(temp/(event_end - event_start))

Shapely_all_params_mean

0 77200
0 77201
0 77202
0 77203
0 77204
0 77205
0 77206
0 77207
0 77208
0 77209
0 77210
0 77211
0 77212
0 77213
0 77214
0 77215
0 77216
0 77217
0 77218
0 77219
0 77220
0 77221
0 77222
0 77223
0 77224
0 77225
0 77226
0 77227
0 77228
0 77229
0 77230
0 77231
0 77232
0 77233
0 77234
0 77235
0 77236
0 77237
0 77238
0 77239
0 77240
0 77241
0 77242
0 77243
0 77244
0 77245
0 77246
0 77247
0 77248
0 77249
0 77250
0 77251
0 77252
0 77253
0 77254
0 77255
0 77256
0 77257
0 77258
0 77259
0 77260
0 77261
0 77262
0 77263
0 77264
0 77265
0 77266
0 77267
0 77268
0 77269
0 77270
0 77271
0 77272
0 77273
0 77274
0 77275
0 77276
0 77277
0 77278
0 77279
0 77280
0 77281
0 77282
0 77283
0 77284
0 77285
0 77286
0 77287
0 77288
0 77289
0 77290
0 77291
0 77292
0 77293
0 77294
0 77295
0 77296
0 77297
0 77298
0 77299
0 77300
0 77301
0 77302
0 77303
0 77304
0 77305
0 77306
0 77307
0 77308
0 77309
0 77310
0 77311
0 77312
0 77313
0 77314
0 77315
0 77316
0 77317
0 77318
0 77319
0 77320
0 77321
0 77322
0 77323
0 77324
0 77325
0 77326
0 77327
0 77328
0 77329
0 77330
0 77331
0 77332
0 77333
0 77334
0 77335
0 77336
0 77337
0 77338
0 77339
0 77340
0 77341
0 77342
0 77343
0 77344
0 77345
0 77346
0 77347
0 77348
0 77349
0 77350
0 77351
0 77352
0 77353
0 77354
0 77355
0 77356
0 77357
0 77358
0 77359
0 77360
0 77361
0 77362
0 77363
0 77364
0 77365
0 77366
0 77367
0 77368
0 77369
0 77370
0 77371
0 77372
0 77373
0 77374
0 77375
0 77376
0 77377
0 77378
0 77379
0 77380
0 77381
0 77382
0 77383
0 77384
0 77385
0 77386
0 77387
0 77388
0 77389
0 77390
0 77391
0 77392
0 77393
0 77394
0 77395
0 77396
0 77397
0 77398
0 77399
0 77400
0 77401
0 77402
0 77403
0 77404
0 77405
0 77406
0 77407
0 77408
0 77409
0 77410
0 77411
0 77412
0 77413
0 77414
0 77415
0 77416
0 77417
0 77418
0 77419
0 77420
0 77421
0 77422
0 77423
0 77424
0 77425
0 77426
0 77427
0 77428
0 77429
0 77430
0 77431
0 77432
0 77433
0 77434
0 77435
0 77436
0 77437
0 77438
0 77439
0 77440
0 77441
0 77442
0 77443
0 77444
0 77445
0 77446
0 77447
0 77448
0 77449
0 77450
0 77451
0 77452
0 77453
0 77454
0 77455
0 77456
0 77457
0 77458
0 77459
0 77460
0 77461
0 77462
0 77463
0 77464
0 77465
0 77466
0 77467
0 77468
0 77469
0 77470
0 77471
0 77472
0 77473
0 77474
0 77475
0 77476
0 77477
0 77478
0 77479
0 77480
0 77481
0 77482
0 77483
0 77484
0 77485
0 77486
0 77487
0 77488
0 77489
0 77490
0 77491
0 77492
0 77493
0 77494
0 77495
0 77496
0 77497
0 77498
0 77499
1 77200
1 77201
1 77202
1 77203
1 77204
1 77205
1 77206
1 77207
1 77208
1 77209
1 77210
1 77211
1 77212
1 77213
1 77214
1 77215
1 77216
1 77217
1 77218
1 77219
1 77220
1 77221
1 77222
1 77223
1 77224
1 77225
1 77226
1 77227
1 77228
1 77229
1 77230
1 77231
1 77232
1 77233
1 77234
1 77235
1 77236
1 77237
1 77238
1 77239
1 77240
1 77241
1 77242
1 77243
1 77244
1 77245
1 77246
1 77247
1 77248
1 77249
1 77250
1 77251
1 77252
1 77253
1 77254
1 77255
1 77256
1 77257
1 77258
1 77259
1 77260
1 77261
1 77262
1 77263
1 77264
1 77265
1 77266
1 77267
1 77268
1 77269
1 77270
1 77271
1 77272
1 77273
1 77274
1 77275
1 77276
1 77277
1 77278
1 77279
1 77280
1 77281
1 77282
1 77283
1 77284
1 77285
1 77286
1 77287
1 77288
1 77289
1 77290
1 77291
1 77292
1 77293
1 77294
1 77295
1 77296
1 77297
1 77298
1 77299
1 77300
1 77301
1 77302
1 77303
1 77304
1 77305
1 77306
1 77307
1 77308
1 77309
1 77310
1 77311
1 77312
1 77313
1 77314
1 77315
1 77316
1 77317
1 77318
1 77319
1 77320
1 77321
1 77322
1 77323
1 77324
1 77325
1 77326
1 77327
1 77328
1 77329
1 77330
1 77331
1 77332
1 77333
1 77334
1 77335
1 77336
1 77337
1 77338
1 77339
1 77340
1 77341
1 77342
1 77343
1 77344
1 77345
1 77346
1 77347
1 77348
1 77349
1 77350
1 77351
1 77352
1 77353
1 77354
1 77355
1 77356
1 77357
1 77358
1 77359
1 77360
1 77361
1 77362
1 77363
1 77364
1 77365
1 77366
1 77367
1 77368
1 77369
1 77370
1 77371
1 77372
1 77373
1 77374
1 77375
1 77376
1 77377
1 77378
1 77379
1 77380
1 77381
1 77382
1 77383
1 77384
1 77385
1 77386
1 77387
1 77388
1 77389
1 77390
1 77391
1 77392
1 77393
1 77394
1 77395
1 77396
1 77397
1 77398
1 77399
1 77400
1 77401
1 77402
1 77403
1 77404
1 77405
1 77406
1 77407
1 77408
1 77409
1 77410
1 77411
1 77412
1 77413
1 77414
1 77415
1 77416
1 77417
1 77418
1 77419
1 77420
1 77421
1 77422
1 77423
1 77424
1 77425
1 77426
1 77427
1 77428
1 77429
1 77430
1 77431
1 77432
1 77433
1 77434
1 77435
1 77436
1 77437
1 77438
1 77439
1 77440
1 77441
1 77442
1 77443
1 77444
1 77445
1 77446
1 77447
1 77448
1 77449
1 77450
1 77451
1 77452
1 77453
1 77454
1 77455
1 77456
1 77457
1 77458
1 77459
1 77460
1 77461
1 77462
1 77463
1 77464
1 77465
1 77466
1 77467
1 77468
1 77469
1 77470
1 77471
1 77472
1 77473
1 77474
1 77475
1 77476
1 77477
1 77478
1 77479
1 77480
1 77481
1 77482
1 77483
1 77484
1 77485
1 77486
1 77487
1 77488
1 77489
1 77490
1 77491
1 77492
1 77493
1 77494
1 77495
1 77496
1 77497
1 77498
1 77499
2 77200
2 77201
2 77202
2 77203
2 77204
2 77205
2 77206
2 77207
2 77208
2 77209
2 77210
2 77211
2 77212
2 77213
2 77214
2 77215
2 77216
2 77217
2 77218
2 77219
2 77220
2 77221
2 77222
2 77223
2 77224
2 77225
2 77226
2 77227
2 77228
2 77229
2 77230
2 77231
2 77232
2 77233
2 77234
2 77235
2 77236
2 77237
2 77238
2 77239
2 77240
2 77241
2 77242
2 77243
2 77244
2 77245
2 77246
2 77247
2 77248
2 77249
2 77250
2 77251
2 77252
2 77253
2 77254
2 77255
2 77256
2 77257
2 77258
2 77259
2 77260
2 77261
2 77262
2 77263
2 77264
2 77265
2 77266
2 77267
2 77268
2 77269
2 77270
2 77271
2 77272
2 77273
2 77274
2 77275
2 77276
2 77277
2 77278
2 77279
2 77280
2 77281
2 77282
2 77283
2 77284
2 77285
2 77286
2 77287
2 77288
2 77289
2 77290
2 77291
2 77292
2 77293
2 77294
2 77295
2 77296
2 77297
2 77298
2 77299
2 77300
2 77301
2 77302
2 77303
2 77304
2 77305
2 77306
2 77307
2 77308
2 77309
2 77310
2 77311
2 77312
2 77313
2 77314
2 77315
2 77316
2 77317
2 77318
2 77319
2 77320
2 77321
2 77322
2 77323
2 77324
2 77325
2 77326
2 77327
2 77328
2 77329
2 77330
2 77331
2 77332
2 77333
2 77334
2 77335
2 77336
2 77337
2 77338
2 77339
2 77340
2 77341
2 77342
2 77343
2 77344
2 77345
2 77346
2 77347
2 77348
2 77349
2 77350
2 77351
2 77352
2 77353
2 77354
2 77355
2 77356
2 77357
2 77358
2 77359
2 77360
2 77361
2 77362
2 77363
2 77364
2 77365
2 77366
2 77367
2 77368
2 77369
2 77370
2 77371
2 77372
2 77373
2 77374
2 77375
2 77376
2 77377
2 77378
2 77379
2 77380
2 77381
2 77382
2 77383
2 77384
2 77385
2 77386
2 77387
2 77388
2 77389
2 77390
2 77391
2 77392
2 77393
2 77394
2 77395
2 77396
2 77397
2 77398
2 77399
2 77400
2 77401
2 77402
2 77403
2 77404
2 77405
2 77406
2 77407
2 77408
2 77409
2 77410
2 77411
2 77412
2 77413
2 77414
2 77415
2 77416
2 77417
2 77418
2 77419
2 77420
2 77421
2 77422
2 77423
2 77424
2 77425
2 77426
2 77427
2 77428
2 77429
2 77430
2 77431
2 77432
2 77433
2 77434
2 77435
2 77436
2 77437
2 77438
2 77439
2 77440
2 77441
2 77442
2 77443
2 77444
2 77445
2 77446
2 77447
2 77448
2 77449
2 77450
2 77451
2 77452
2 77453
2 77454
2 77455
2 77456
2 77457
2 77458
2 77459
2 77460
2 77461
2 77462
2 77463
2 77464
2 77465
2 77466
2 77467
2 77468
2 77469
2 77470
2 77471
2 77472
2 77473
2 77474
2 77475
2 77476
2 77477
2 77478
2 77479
2 77480
2 77481
2 77482
2 77483
2 77484
2 77485
2 77486
2 77487
2 77488
2 77489
2 77490
2 77491
2 77492
2 77493
2 77494
2 77495
2 77496
2 77497
2 77498
2 77499
3 77200
3 77201
3 77202
3 77203
3 77204
3 77205
3 77206
3 77207
3 77208
3 77209
3 77210
3 77211
3 77212
3 77213
3 77214
3 77215
3 77216
3 77217
3 77218
3 77219
3 77220
3 77221
3 77222
3 77223
3 77224
3 77225
3 77226
3 77227
3 77228
3 77229
3 77230
3 77231
3 77232
3 77233
3 77234
3 77235
3 77236
3 77237
3 77238
3 77239
3 77240
3 77241
3 77242
3 77243
3 77244
3 77245
3 77246
3 77247
3 77248
3 77249
3 77250
3 77251
3 77252
3 77253
3 77254
3 77255
3 77256
3 77257
3 77258
3 77259
3 77260
3 77261
3 77262
3 77263
3 77264
3 77265
3 77266
3 77267
3 77268
3 77269
3 77270
3 77271
3 77272
3 77273
3 77274
3 77275
3 77276
3 77277
3 77278
3 77279
3 77280
3 77281
3 77282
3 77283
3 77284
3 77285
3 77286
3 77287
3 77288
3 77289
3 77290
3 77291
3 77292
3 77293
3 77294
3 77295
3 77296
3 77297
3 77298
3 77299
3 77300
3 77301
3 77302
3 77303
3 77304
3 77305
3 77306
3 77307
3 77308
3 77309
3 77310
3 77311
3 77312
3 77313
3 77314
3 77315
3 77316
3 77317
3 77318
3 77319
3 77320
3 77321
3 77322
3 77323
3 77324
3 77325
3 77326
3 77327
3 77328
3 77329
3 77330
3 77331
3 77332
3 77333
3 77334
3 77335
3 77336
3 77337
3 77338
3 77339
3 77340
3 77341
3 77342
3 77343
3 77344
3 77345
3 77346
3 77347
3 77348
3 77349
3 77350
3 77351
3 77352
3 77353
3 77354
3 77355
3 77356
3 77357
3 77358
3 77359
3 77360
3 77361
3 77362
3 77363
3 77364
3 77365
3 77366
3 77367
3 77368
3 77369
3 77370
3 77371
3 77372
3 77373
3 77374
3 77375
3 77376
3 77377
3 77378
3 77379
3 77380
3 77381
3 77382
3 77383
3 77384
3 77385
3 77386
3 77387
3 77388
3 77389
3 77390
3 77391
3 77392
3 77393
3 77394
3 77395
3 77396
3 77397
3 77398
3 77399
3 77400
3 77401
3 77402
3 77403
3 77404
3 77405
3 77406
3 77407
3 77408
3 77409
3 77410
3 77411
3 77412
3 77413
3 77414
3 77415
3 77416
3 77417
3 77418
3 77419
3 77420
3 77421
3 77422
3 77423
3 77424
3 77425
3 77426
3 77427
3 77428
3 77429
3 77430
3 77431
3 77432
3 77433
3 77434
3 77435
3 77436
3 77437
3 77438
3 77439
3 77440
3 77441
3 77442
3 77443
3 77444
3 77445
3 77446
3 77447
3 77448
3 77449
3 77450
3 77451
3 77452
3 77453
3 77454
3 77455
3 77456
3 77457
3 77458
3 77459
3 77460
3 77461
3 77462
3 77463
3 77464
3 77465
3 77466
3 77467
3 77468
3 77469
3 77470
3 77471
3 77472
3 77473
3 77474
3 77475
3 77476
3 77477
3 77478
3 77479
3 77480
3 77481
3 77482
3 77483
3 77484
3 77485
3 77486
3 77487
3 77488
3 77489
3 77490
3 77491
3 77492
3 77493
3 77494
3 77495
3 77496
3 77497
3 77498
3 77499
4 77200
4 77201
4 77202
4 77203
4 77204
4 77205
4 77206
4 77207
4 77208
4 77209
4 77210
4 77211
4 77212
4 77213
4 77214
4 77215
4 77216
4 77217
4 77218
4 77219
4 77220
4 77221
4 77222
4 77223
4 77224
4 77225
4 77226
4 77227
4 77228
4 77229
4 77230
4 77231
4 77232
4 77233
4 77234
4 77235
4 77236
4 77237
4 77238
4 77239
4 77240
4 77241
4 77242
4 77243
4 77244
4 77245
4 77246
4 77247
4 77248
4 77249
4 77250
4 77251
4 77252
4 77253
4 77254
4 77255
4 77256
4 77257
4 77258
4 77259
4 77260
4 77261
4 77262
4 77263
4 77264
4 77265
4 77266
4 77267
4 77268
4 77269
4 77270
4 77271
4 77272
4 77273
4 77274
4 77275
4 77276
4 77277
4 77278
4 77279
4 77280
4 77281
4 77282
4 77283
4 77284
4 77285
4 77286
4 77287
4 77288
4 77289
4 77290
4 77291
4 77292
4 77293
4 77294
4 77295
4 77296
4 77297
4 77298
4 77299
4 77300
4 77301
4 77302
4 77303
4 77304
4 77305
4 77306
4 77307
4 77308
4 77309
4 77310
4 77311
4 77312
4 77313
4 77314
4 77315
4 77316
4 77317
4 77318
4 77319
4 77320
4 77321
4 77322
4 77323
4 77324
4 77325
4 77326
4 77327
4 77328
4 77329
4 77330
4 77331
4 77332
4 77333
4 77334
4 77335
4 77336
4 77337
4 77338
4 77339
4 77340
4 77341
4 77342
4 77343
4 77344
4 77345
4 77346
4 77347
4 77348
4 77349
4 77350
4 77351
4 77352
4 77353
4 77354
4 77355
4 77356
4 77357
4 77358
4 77359
4 77360
4 77361
4 77362
4 77363
4 77364
4 77365
4 77366
4 77367
4 77368
4 77369
4 77370
4 77371
4 77372
4 77373
4 77374
4 77375
4 77376
4 77377
4 77378
4 77379
4 77380
4 77381
4 77382
4 77383
4 77384
4 77385
4 77386
4 77387
4 77388
4 77389
4 77390
4 77391
4 77392
4 77393
4 77394
4 77395
4 77396
4 77397
4 77398
4 77399
4 77400
4 77401
4 77402
4 77403
4 77404
4 77405
4 77406
4 77407
4 77408
4 77409
4 77410
4 77411
4 77412
4 77413
4 77414
4 77415
4 77416
4 77417
4 77418
4 77419
4 77420
4 77421
4 77422
4 77423
4 77424
4 77425
4 77426
4 77427
4 77428
4 77429
4 77430
4 77431
4 77432
4 77433
4 77434
4 77435
4 77436
4 77437
4 77438
4 77439
4 77440
4 77441
4 77442
4 77443
4 77444
4 77445
4 77446
4 77447
4 77448
4 77449
4 77450
4 77451
4 77452
4 77453
4 77454
4 77455
4 77456
4 77457
4 77458
4 77459
4 77460
4 77461
4 77462
4 77463
4 77464
4 77465
4 77466
4 77467
4 77468
4 77469
4 77470
4 77471
4 77472
4 77473
4 77474
4 77475
4 77476
4 77477
4 77478
4 77479
4 77480
4 77481
4 77482
4 77483
4 77484
4 77485
4 77486
4 77487
4 77488
4 77489
4 77490
4 77491
4 77492
4 77493
4 77494
4 77495
4 77496
4 77497
4 77498
4 77499
5 77200
5 77201
5 77202
5 77203
5 77204
5 77205
5 77206
5 77207
5 77208
5 77209
5 77210
5 77211
5 77212
5 77213
5 77214
5 77215
5 77216
5 77217
5 77218
5 77219
5 77220
5 77221
5 77222
5 77223
5 77224
5 77225
5 77226
5 77227
5 77228
5 77229
5 77230
5 77231
5 77232
5 77233
5 77234
5 77235
5 77236
5 77237
5 77238
5 77239
5 77240
5 77241
5 77242
5 77243
5 77244
5 77245
5 77246
5 77247
5 77248
5 77249
5 77250
5 77251
5 77252
5 77253
5 77254
5 77255
5 77256
5 77257
5 77258
5 77259
5 77260
5 77261
5 77262
5 77263
5 77264
5 77265
5 77266
5 77267
5 77268
5 77269
5 77270
5 77271
5 77272
5 77273

In [81]:
plt.bar( ["N", "V", "Bz", "sigma Bz", "NM", "DST_t"], Shapely_all_params_mean)

In [58]:
import random
random.sample([0,1,2,3,4,5], k=random.randint(0,  5))

[0, 4, 5, 2, 1]